### ISSUE TITLE
Always white when lighting up

### ISSUE THREAD

**Issue by Lyliya** [dave-code-ruiz/elkbledom#12]
Hey,

Thanks for your plugin, it was really what i was looking for !
But i would like to keep the same color every time i turn it on/off. Unfortunately, it always go white, is there any reason for that ?
Is there a way for me to keep the last used color ?

Thanks,

Lyliya

**Comment by dave-code-ruiz** [comment]
If you go to "Settings" - "Devices and Services" - "elkbledom integration" - "Configure" you can deactivate reset white, and solved it partially. 
This integration have a bug, I cannot know state of led strip and therefore generate issues like this in integration

**Comment by dave-code-ruiz** [comment]
I tomorrow will upload New versión with this option

**Comment by dave-code-ruiz** [comment]
I create new version 1.0.0 which solves partially your issue, please test it and close issue if it is works

**Comment by Lyliya** [comment]
With the new update, i get an error when turning on/off


![image](https://user-images.githubusercontent.com/22936229/209950049-7ec83079-beb2-4da8-aa5c-c898e091b35c.png)

**Comment by dave-code-ruiz** [comment]
Try in HomeAssistant use debug log to see more information of posible errors. i need device discover information that show in debug logs

In configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.elkbledom: debug
```

**Comment by Lyliya** [comment]
The ledstrip got disconnected, and i dont seem to get it to be connected anymore. I got this log message

```
2022-12-29 13:37:44.672 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Connecting; RSSI: -70
2022-12-29 13:38:22.265 WARNING (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Device unexpectedly disconnected; RSSI: -70
2022-12-29 13:38:28.343 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Connected; RSSI: -70
2022-12-29 13:38:28.344 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Subscribe to notifications; RSSI: -70
2022-12-29 13:38:28.618 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Stop
2022-12-29 13:38:31.186 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Disconnected from device; RSSI: -70
2022-12-29 13:39:40.425 ERROR (MainThread) [frontend.js.latest.202212131] :0:0 ResizeObserver loop completed with undelivered notifications.
2022-12-29 13:39:45.084 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Connecting; RSSI: -70
2022-12-29 13:39:49.779 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Connected; RSSI: -70
2022-12-29 13:39:49.780 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Subscribe to notifications; RSSI: -70
2022-12-29 13:39:50.315 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Stop
2022-12-29 13:39:52.203 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Disconnected from device; RSSI: -70
2022-12-29 13:40:07.452 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Connecting; RSSI: -70
2022-12-29 13:40:07.816 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Connected; RSSI: -70
2022-12-29 13:40:07.817 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Subscribe to notifications; RSSI: -70
2022-12-29 13:40:08.352 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Stop
2022-12-29 13:40:10.254 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDON: Disconnected from device; RSSI: -70
```

**Comment by Lyliya** [comment]
It look like an issue on my end. It look like i cant connect to the ledstrip, neither from bluetoothctl nor my homebridge plugin to control it

![image](https://user-images.githubusercontent.com/22936229/209953875-dd33ab86-54e0-407b-bb4a-01de856d06fb.png)

**Comment by dave-code-ruiz** [comment]
Try to delete integration and re-add it , name of device "ELK-BLEDON" in log is and error, name can be "ELK-BLEDOM" if you asked for this name type it correct.

Report before logs and if you use "manual mac" or HA detect it

There are possible distance error between HA and Led strip

Thanks,

**Comment by Lyliya** [comment]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/elkbledom/elkbledom.py:150
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 14:46:05 (2 occurrences)
Last logged: 14:46:28

    [547795707040] 'NoneType' object is not iterable
    [547795705600] 'NoneType' object is not iterable

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 570, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/elkbledom/light.py", line 136, in async_turn_on
    await self._instance.turn_on()
  File "/config/custom_components/elkbledom/elkbledom.py", line 91, in _async_wrap_retry_bluetooth_connection_error
    return await func(self, *args, **kwargs)
  File "/config/custom_components/elkbledom/elkbledom.py", line 208, in turn_on
    await self._write(self._turn_on_cmd)
  File "/config/custom_components/elkbledom/elkbledom.py", line 147, in _write
    await self._write_while_connected(data)
  File "/config/custom_components/elkbledom/elkbledom.py", line 150, in _write_while_connected
    LOGGER.debug(''.join(format(x, ' 03x') for x in data))
TypeError: 'NoneType' object is not iterable
```

**Comment by dave-code-ruiz** [comment]
Ok, i update code, manual MAC meaning that you have something different in your led strip and is more dificult detect it.

Please, update new version 1.0.1 , activate debug logs , and post results.

Thanks

**Comment by dave-code-ruiz** [comment]
Other cuestion, can you help me to translate to french?

```
{
    "config": {
        "step": {
            "user": {
                "data": {
                    "mac": "Bluetooth MAC address",
                    "name": "Name"
                },
                "title": "Pick a Elkbledom light. Make sure light in sight for validation."
            },
            "validate": {
                "data": {
                    "retry": "Retry validate connection?",
                    "flicker": "Did the light blink?"
                },
                "title": "Validate Elkbledom connection"
            },
            "manual": {
                "data": {
                    "mac": "Bluetooth MAC address",
                    "name": "Name"
                },
                "title": "Enter bluetooth MAC address"
            }
        },
        "error": {
            "connect": "Unable to connect to Elkbledom"
        },
        "abort": {
            "cannot_validate": "Unable to validate Elkbledom light",
            "cannot_connect": "Unable to connect to Elkbledom"
        }
    },
    "options": {
        "step": {
          "user": {
            "data": {
              "reset": "Reset color when led turn on"
            }
          }
        }
      },
    "title": "Elkbledom"
}
```
just answer me with this texts in french

**Comment by Lyliya** [comment]
Auto-detect work fine and the light is now responding ! Thank you :D

Sure

```
{
    "config": {
        "step": {
            "user": {
                "data": {
                    "mac": "Adresse MAC Bluetooth",
                    "name": "Nom"
                },
                "title": "Sélectionner une lumière Elkbledom."
            },
            "validate": {
                "data": {
                    "retry": "Réessayer de se connecter ?",
                    "flicker": "La lumière à-t-elle clignoté ?"
                },
                "title": "Valider la connexion"
            },
            "manual": {
                "data": {
                    "mac": "Adresse MAC Bluetooth",
                    "name": "Nom"
                },
                "title": "Entrer une adresse MAC Bluetooth"
            }
        },
        "error": {
            "connect": "Echec de la connexion à Elkbledom"
        },
        "abort": {
            "cannot_validate": "Echec de validation de la lumière Elkbledom",
            "cannot_connect": "Echec de la connexion à Elkbledom"
        }
    },
    "options": {
        "step": {
          "user": {
            "data": {
              "reset": "Réinitialiser la couleur à l'allumage"
            }
          }
        }
      },
    "title": "Elkbledom"
}
```

**Comment by dave-code-ruiz** [comment]
Great news.
Thanks for translate
I close issue, if you need more, create new issue
Thanks
