### ISSUE TITLE
Adding Light strip fails

### ISSUE THREAD

**Issue by ehspill** [dave-code-ruiz/elkbledom#47]
Hi, i can not add the strip, it runs into a timeout while trying to connect.

Strip: https://amzn.eu/d/hCpoa3l (Ailbton 10m BT Neon Strip)
Home Assistant: Supervisor 2023.10.0 @OS 10.5 running on x86 Intel NUC
BT: tried onboard BT, external USB BT 5.0 and 5.3 Adapters.

UUID:
![image](https://allthingscitrix.com/www/01.jpg)

The Integration does find the Strip:
![image](https://allthingscitrix.com/www/02.jpg)

But fails to connect:
![image](https://allthingscitrix.com/www/03.jpg)

Logs:
`2023-10-06 20:43:13.154 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered bluetooth devices, step bluetooth, : BE:67:00:25:6D:E0 , ELK-BLEDOM00              
2023-10-06 20:43:13.154 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered bluetooth devices, step bluetooth confirm, : None                                   
2023-10-06 20:43:13.154 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered supported devices: ELK-BLEDOM00 - BE:67:00:25:6D:E0 - -127
2023-10-06 20:44:12.750 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered supported devices: ELK-BLEDOM00 - BE:67:00:25:6D:E0 - -127
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] device ELK-BLEDOM00: BE:67:00:25:6D:E0 -46
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] Model information for device ELK-BLEDOM00 : ModelNo ELK-BLE, Turn on cmd [126, 0, 4, 240, 0, 1, 255, 0, 239], Turn off cmd [126, 0, 4, 0, 0, 0, 255, 0, 239], rssi -46
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] init command for: ELK-BLEDOM00 not needed; RSSI: -46
2023-10-06 20:43:13.154 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered bluetooth devices, step bluetooth, : BE:67:00:25:6D:E0 , ELK-BLEDOM00               
2023-10-06 20:43:13.154 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered bluetooth devices, step bluetooth confirm, : None
2023-10-06 20:43:13.154 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered supported devices: ELK-BLEDOM00 - BE:67:00:25:6D:E0 - -127                                                              
2023-10-06 20:44:12.750 DEBUG (MainThread) [custom_components.elkbledom.config_flow] Discovered supported devices: ELK-BLEDOM00 - BE:67:00:25:6D:E0 - -127
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] device ELK-BLEDOM00: BE:67:00:25:6D:E0 -46
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] Model information for device ELK-BLEDOM00 : ModelNo ELK-BLE, Turn on cmd [126, 0, 4, 240, 0, 1, 255, 0, 239], Turn off cmd [126, 0, 4, 0, 0, 0, 255, 0, 239], rssi -46                     
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] init command for: ELK-BLEDOM00 not needed; RSSI: -46
2023-10-06 20:44:22.550 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDOM00: Connecting; RSSI: -46                                                              
2023-10-06 20:45:43.602 ERROR (MainThread) [custom_components.elkbledom.elkbledom] Error getting status: ELK-BLEDOM00 - BE:67:00:25:6D:E0: Failed to connect after 4 attempt(s): TimeoutError                                                                               

2023-10-06 20:45:43.616 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] Traceback (most recent call last):                                                                 
File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect reply = await self.bus.call(
^^^^^^^^^^^^^^^^^^^^^    
File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 399, in call await future asyncio.exceptions.CancelledError                                                         
The above exception was the direct cause of the following exception:                      
Traceback (most recent call last):                                                          
File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/init.py", line 350, in establish_connection await client.connect(
File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 292, in connect connected = await super().connect(**kwargs)                                                           
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             
File "/usr/local/lib/python3.11/site-packages/bleak/init.py", line 605, in connect return await self._backend.connect(**kwargs) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            
File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect async with async_timeout(timeout):                                                      
File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit_ raise TimeoutError from exc_val 
TimeoutError 
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/elkbledom/elkbledom.py", line 407, in update                await self._ensure_connected()
  File "/config/custom_components/elkbledom/elkbledom.py", line 455, in _ensure_connected
    client = await establish_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/_init_.py", line 374, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/_init_.py", line 314, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc                                                bleak_retry_connector.BleakNotFoundError: ELK-BLEDOM00 - BE:67:00:25:6D:E0: Failed to connect after 4 attempt(s): TimeoutError
2023-10-06 20:45:43.617 DEBUG (MainThread) [custom_components.elkbledom.elkbledom] ELK-BLEDOM00: Connecting; RSSI: -46`

any idea?
regards,
Sven

**Comment by dave-code-ruiz** [comment]
Same like #45 

Hi, The integration does not manage the connections , this error is throws from the bleak library (https://pypi.org/project/bleak/) it is possible to be distance error , or strip is connected to other device, or the strip staying blocked (try turn off, turn on), or something similar, but integration is not the problem

May be too and issue from bleak library,  you need to investigate it

**Comment by ehspill** [comment]
Hi,

- distance cant be an issue, the rssi is at -45, its right next to the bt stick.
- the strip is not paired to any device
- i unplugged/plugged the strip multiple times
- i reset the strip
- i have no issues with other bt addins uding bleak

**Comment by dilpish** [comment]
> * distance cant be an issue, the rssi is at -45, its right next to the bt stick.

I had a similar problem with an LED strip when I used weak USB power. I connected it to a more powerful power supply and everything worked out.

**Comment by dave-code-ruiz** [comment]
Great, thanks for your information and share your solution

**Comment by ehspill** [comment]
tried with bench power supply, no difference, same voltage and currennt drawn.

**Comment by ehspill** [comment]
did not change anything, im ordering a new controller wirh tuya.

**Comment by dave-code-ruiz** [comment]
Same like #45
