### ISSUE TITLE
Logger: custom_components.elkbledom.elkbledom

### ISSUE THREAD

**Issue by Next9999** [dave-code-ruiz/elkbledom#5]
Hello

Connection broke since the last release

https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes

-------------------------------
Error
Config flow could not be loaded: undefined

**Comment by dave-code-ruiz** [comment]
I update to new release 2022.7.4 and initially led strip not work, and show me connection errors.

When I remove integration and re-add it, then work fine.

Try it and post results.

Thnks

**Comment by dave-code-ruiz** [comment]
Now i think it isn´t your problem.

In other repository i can see:

> I had this issue also but I am running with a supervised install of HA on Debian. The issue was the base OS didnt have Bluez installed, installed it and thats solved now so I imagine your installs for whatever reason do not have access to the BT module/device.

I think it is your problem, try solved it

**Comment by Next9999** [comment]
Hi... i have remove the integration, delete the entity and reboot my raspberry

then re-install the integration, reboot then add the entity

here is the system error
Config flow could not be loaded: undefined
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/elkbledom/elkbledom.py:51
Integration: Elkbledom (documentation, issues)
First occurred: 14:38:17 (1 occurrences)
Last logged: 14:38:17

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/elkbledom/config_flow.py", line 38, in async_step_user
    devices = await discover()
  File "/config/custom_components/elkbledom/elkbledom.py", line 51, in discover
    devices = await BleakScanner.discover()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 115, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 155, in start
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.NotReady] Resource Not Ready

**Comment by Next9999** [comment]
i ran the command bluetoothctl -v

bluetoothctl: 5.64

**Comment by Next9999** [comment]
![image](https://user-images.githubusercontent.com/54117519/179060465-198cec9e-cabc-4df0-8ade-389459008f99.png)

**Comment by dave-code-ruiz** [comment]
Exec command:

hcitool dev

And post results

Thnks

**Comment by dave-code-ruiz** [comment]
Show this issue for more info, it is config BlueZ or bluetooth device error:

https://github.com/sysofwan/ha-triones/issues/15

**Comment by Next9999** [comment]
Leds are back on line
