### ISSUE TITLE
Cannot configure LotusLamp strip (worked before)

### ISSUE THREAD

**Issue by Hans-Arno** [dave-code-ruiz/elkbledom#60]
In September I bought a LED strip [https://www.amazon.de/gp/product/B0CBBLQ8WH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1] and was happy when I found out, that it was controllable by Home Assistant through this HACS integration,
After an update it stopped working and I had to delete the integration, but downgrading did not help.
With latest version, configuring after installation of HACS integration and  restart leads to:

`2024-02-04 08:51:08.173 ERROR (MainThread) [root] A message handler raised an exception: Cannot convert home_assistant_bluetooth.models.BluetoothServiceInfoBleak to habluetooth.models.BluetoothServiceInfoBleak
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 798, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/home/homeassistant/.homeassistant/deps/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 979, in _parse_msg
    self._run_advertisement_callbacks(
  File "/home/homeassistant/.homeassistant/deps/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 1028, in _run_advertisement_callbacks
    callback(device_path, device.copy())
  File "/home/homeassistant/.homeassistant/deps/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 270, in _handle_advertising_data
    self.call_detection_callbacks(device, advertisement_data)
  File "/home/homeassistant/.homeassistant/deps/lib/python3.11/site-packages/bleak/backends/scanner.py", line 210, in call_detection_callbacks
    callback(device, advertisement_data)
  File "src/habluetooth/scanner.py", line 179, in habluetooth.scanner.HaScanner._async_detection_callback
  File "src/habluetooth/scanner.py", line 204, in habluetooth.scanner.HaScanner._async_detection_callback
  File "src/habluetooth/manager.py", line 398, in habluetooth.manager.BluetoothManager.scanner_adv_received
  File "src/habluetooth/manager.py", line 398, in habluetooth.manager.BluetoothManager.scanner_adv_received
  File "src/habluetooth/manager.py", line 437, in habluetooth.manager.BluetoothManager.scanner_adv_received
TypeError: Cannot convert home_assistant_bluetooth.models.BluetoothServiceInfoBleak to habluetooth.models.BluetoothServiceInfoBleak`

I guess I cannot work around any more :-(

**Comment by dave-code-ruiz** [comment]
Ok, i think you have a problem between home_assistant_bluetooth library and HA versions.

Maybe it is something similar that: https://github.com/home-assistant/core/issues/84584

Maybe you need to add bluetooth integration in Settings - Integrations - add integration - search Bluetooth

Maybe you need to update HA and my integration to lastest version

Try all i saw you, and post with your versions of HA , and libraries bleak and home_assistant_bluetooth

**Comment by Hans-Arno** [comment]
> Maybe it is something similar that: https://github.com/home-assistant/core/issues/84584

Yeah, that was it: the home_assistant_bluetooth*-directories showed version 10, but the python dependencies already 12.
Deleting both directories, downgrade and upgrade again did the trick.

Thanks!

**Comment by Hans-Arno** [comment]
Hint from Dave was successful.
