### ISSUE TITLE
 Rxment 300ft Outdoor LED Strip Lights IP68 Waterproof, Color Changing, Music Sync, Remote & App Control

### ISSUE THREAD

**Issue by wattsjus** [dave-code-ruiz/elkbledom#72]
I have Rxment brand led strip lights.  Elkbledom can reconize the bluetooth controller but every time it tries to connect it timesout.  I've tried configuring the bluetooth tracker and lots of other things to make it connect easier but nothing seems to be working.  I have two controllers and each are giving the same issue.

This is a trace I received by logging the debug information:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 286, in connect
    wrapped_backend = self._async_get_best_available_backend_and_device(manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 395, in _async_get_best_available_backend_and_device
    raise BleakError(
bleak.exc.BleakError: No backend with an available connection slot that can reach address ...................... was found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/elkbledom/elkbledom.py", line 112, in _async_wrap_retry_bluetooth_connection_error
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elkbledom/elkbledom.py", line 372, in turn_on
    await self._write(self._turn_on_cmd)
  File "/config/custom_components/elkbledom/elkbledom.py", line 265, in _write
    await self._ensure_connected()
  File "/config/custom_components/elkbledom/elkbledom.py", line 457, in _ensure_connected
    client = await establish_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 472, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 332, in _raise_if_needed
    raise BleakOutOfConnectionSlotsError(
bleak_retry_connector.BleakOutOfConnectionSlotsError: ELK-BLEDOM       - ................: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address .................. was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device

**Comment by dave-code-ruiz** [comment]
Sorry i cant help you , 

This is a know issue  https://github.com/dave-code-ruiz/elkbledom/tree/1.1.7?tab=readme-ov-file#known-issues

Only one device can connect to strip , 

I use api https://github.com/hbldh/bleak and this code trows the exception
