### ISSUE TITLE
Controlling brightness not working. 

### ISSUE THREAD

**Issue by Abe-Telo** [dave-code-ruiz/elkbledom#75]
Controlling brightness not working. 

Some color buttons also does not work. 

The W icon (Set White) Also not working.  (No logs on that)

RGB Worked great.

![image](https://github.com/user-attachments/assets/53c44886-682d-4c1c-a8e6-8aeadcb38de2)

![image](https://github.com/user-attachments/assets/31233e0f-965a-49bc-a400-af20085077b1)

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:57:43 AM (12 occurrences)
Last logged: 3:06:34 AM

[139728288912656] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/elkbledom/light.py", line 123, in async_turn_on
    await self._instance.set_color_temp_kelvin(kwargs[ATTR_COLOR_TEMP_KELVIN], None)
  File "/config/custom_components/elkbledom/elkbledom.py", line 112, in _async_wrap_retry_bluetooth_connection_error
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elkbledom/elkbledom.py", line 338, in set_color_temp_kelvin
    brightness_percent = int(brightness * 100 / 255)
                            ~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:03:28 AM (1 occurrences)
Last logged: 3:03:28 AM

[139728288912656] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/elkbledom/light.py", line 117, in async_turn_on
    await self._instance.set_brightness(kwargs[ATTR_BRIGHTNESS])
  File "/config/custom_components/elkbledom/elkbledom.py", line 112, in _async_wrap_retry_bluetooth_connection_error
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elkbledom/elkbledom.py", line 355, in set_brightness
    await self._write([0x7e, 0x04, 0x01, int(intensity*100/255), 0xff, 0x00, 0xff, 0x00, 0xef])
  File "/config/custom_components/elkbledom/elkbledom.py", line 265, in _write
    await self._ensure_connected()
  File "/config/custom_components/elkbledom/elkbledom.py", line 480, in _ensure_connected
    await client.start_notify(self._read_uuid, self._notification_handler)
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 827, in start_notify
    characteristic = self.services.get_characteristic(char_specifier)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/service.py", line 179, in get_characteristic
    uuid = normalize_uuid_str(str(specifier))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/uuids.py", line 1240, in normalize_uuid_str
    return str(UUID(uuid))
               ^^^^^^^^^^
  File "/usr/local/lib/python3.12/uuid.py", line 179, in __init__
    int = int_(hex, 16)
          ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: '0000None00001000800000805f9b34fb'
```

**Comment by dave-code-ruiz** [comment]
Please verificar new versión,

I think it solves now, if not, put init log and error log please

Thanks for you reply

**Comment by dave-code-ruiz** [comment]
Please @Abe-Telo can you test new version 1.3.0 ? 

i think could solves your issue

post here your test results.
